const CACHE="printbook-v5.19.6-order-center-submit-watchdog";
const CORE_ASSETS=["./","./index.html","./styles.css","./storefront-v55.css","./app.js","./cart-edit.js","./stock-adjust.js","./checkout-payment.js","./direct-order-flow.js","./store-qr.png"];

self.addEventListener("install",event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.allSettled(CORE_ASSETS.map(async asset=>{try{const req=new Request(asset,{cache:"reload"});const res=await fetch(req);if(res.ok)await cache.put(req,res.clone())}catch(err){console.warn("PrintBook cache skipped",asset,err)}}));await self.skipWaiting()})())});
self.addEventListener("activate",event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
async function buildCombinedAppResponse(request){const addonUrls=["./cart-edit.js","./stock-adjust.js","./checkout-payment.js","./direct-order-flow.js"].map(x=>new URL(x,self.registration.scope).href);try{const responses=await Promise.all([fetch(new Request(request,{cache:"no-store"})),...addonUrls.map(url=>fetch(new Request(url,{cache:"no-store"})))]);const core=responses.shift();if(!core.ok)return core;const pieces=[await core.text()];for(const addon of responses)if(addon.ok)pieces.push(await addon.text());const source=pieces.join("\n;\n");const headers=new Headers(core.headers);headers.set("Content-Type","application/javascript; charset=utf-8");headers.delete("Content-Length");headers.delete("content-length");const combined=new Response(source,{status:core.status,statusText:core.statusText,headers});const cache=await caches.open(CACHE);cache.put(request,combined.clone()).catch(()=>{});return combined}catch{const cached=await caches.match(request,{ignoreSearch:true});return cached||new Response("",{status:504,statusText:"Offline"})}}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(event.request.mode==="navigate"){event.respondWith((async()=>{try{const fresh=await fetch(event.request);const cache=await caches.open(CACHE);cache.put("./index.html",fresh.clone()).catch(()=>{});return fresh}catch{return(await caches.match(event.request))||(await caches.match("./index.html"))||new Response("PrintBook is offline.",{status:503,headers:{"Content-Type":"text/plain"}})}})());return}if(/\/app\.js$/.test(url.pathname)){event.respondWith(buildCombinedAppResponse(event.request));return}event.respondWith((async()=>{const critical=/\/(styles\.css|storefront-v55\.css|cart-edit\.js|stock-adjust\.js|checkout-payment\.js|direct-order-flow\.js)$/.test(url.pathname);if(critical){try{const fresh=await fetch(new Request(event.request,{cache:"no-store"}));if(fresh.ok){const cache=await caches.open(CACHE);cache.put(event.request,fresh.clone()).catch(()=>{})}return fresh}catch{const cached=await caches.match(event.request,{ignoreSearch:true});return cached||new Response("",{status:504,statusText:"Offline"})}}const cached=await caches.match(event.request);if(cached)return cached;try{const fresh=await fetch(event.request);if(fresh.ok){const cache=await caches.open(CACHE);cache.put(event.request,fresh.clone()).catch(()=>{})}return fresh}catch{return new Response("",{status:504,statusText:"Offline"})}})())});
self.addEventListener("push",event=>{let payload={title:"PrintBook",body:"You have a new PrintBook alert.",tag:"printbook",url:"./"};try{if(event.data)payload={...payload,...event.data.json()}}catch{try{payload.body=event.data.text()}catch{}}const url=new URL(payload.url||"./",self.registration.scope).href;event.waitUntil(self.registration.showNotification(payload.title||"PrintBook",{body:payload.body||"",icon:new URL("./assets/icon-180.png",self.registration.scope).href,badge:new URL("./assets/icon-180.png",self.registration.scope).href,tag:payload.tag||"printbook",renotify:payload.renotify!==false,requireInteraction:payload.requireInteraction===true,data:{url,order_id:payload.order_id||null,type:payload.type||"general"}}))});
self.addEventListener("notificationclick",event=>{event.notification.close();const target=event.notification?.data?.url||self.registration.scope;event.waitUntil((async()=>{const windows=await clients.matchAll({type:"window",includeUncontrolled:true});for(const client of windows){if("focus" in client){try{if("navigate" in client)await client.navigate(target)}catch{}return client.focus()}}return clients.openWindow(target)})())});
self.addEventListener("message",event=>{if(event.data?.type==="SKIP_WAITING")self.skipWaiting()});
